### ISSUE TITLE
How to fix general cors error

### ISSUE THREAD

**Issue by OlympuJupiter** [OlympuJupiter/astronomer-providers#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dtoyoda10** [comment]
Solution 1: Configure the Backend to Allow CORS
Solution 2: Use a Proxy Server
Solution 3: Bypass the Error Using a Browser Extension

Please try this

**Comment by OlympuJupiter** [comment]
I got other errors. but I followed your opinion.
please help me

**Comment by dtoyoda10** [comment]
please try on your hosting server
I think you tried on your local pc and this is wrong way

**Comment by OlympuJupiter** [comment]
great!
thanks
